POST https://localhost:7053/watch
Content-Type: application/json

{
    "movie_id": "04226149-f6af-46de-aaa1-d7c0bbf88b09",
    "user_id": "682671f8-00f1-4155-8416-8b4f3ff97126"
}

###
POST https://localhost:7053/topic
Content-Type: application/json

{
    "movie_id": "04226149-f6af-46de-aaa1-d7c0bbf88b09",
    "topic": "Fiction"
}