# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  MYSQL_DATABASE: movie_sys
  MYSQL_ALLOW_EMPTY_PASSWORD: password
  MYSQL_PASSWORD: password
  MYSQL_HOST: mysql-master
  NODE_ENV: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup MySQL
        # You may pin to the exact commit or the version.
        # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
        uses: mirromutth/mysql-action@v1.1
        with:
          # The port of host
          host port: 3306
          # The port of container
          container port: 3306
          # --character-set-server - The character set of MySQL server
          character set server: utf8mb4
          # --collation-server - The character collation of MySQL server
          collation server: utf8mb4_general_ci
          # Version of MySQL to use
          mysql version: latest
          # MYSQL_ROOT_PASSWORD - root superuser password
          mysql root password: password
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: movie_sys
          # MYSQL_USER - create the specified user with superuser power for created database
          mysql user: root
          # MYSQL_PASSWORD - specified superuser password which user is power for created database
          mysql password: password
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pip package
        run: pip install pymysql
      - name: Run Python script
        run: python Init.py
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
